name: publish-release

on:
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    name: publish-release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.100
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install npm dependencies (ng-spark-auth)
      run: npm ci
      working-directory: packages/ng-spark-auth

    - name: Build ng-spark-auth
      run: dotnet build packages/ng-spark-auth/ng-spark-auth.esproj --configuration Release

    - name: Install dependencies
      run: dotnet restore
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --no-build --configuration Release /p:ContinuousIntegrationBuild=true

    - name: PushNuget
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_TO_NUGET_ORG }} --skip-duplicate

    - name: PushGithub
      run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - name: Push ng-spark-auth to NPM
      uses: JS-DevTools/npm-publish@v4
      with:
        package: 'packages/ng-spark-auth/dist/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_TO_NPMJS }}
        access: 'public'
        provenance: true

    - name: Push ng-spark-auth to Github
      uses: JS-DevTools/npm-publish@v4
      with:
        package: 'packages/ng-spark-auth/dist/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true
